networks:
  openmanus-dev-network:
    driver: bridge
services:
  openmanus-core-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev.api
    cap_add:
    - SYS_ADMIN
    - NET_ADMIN
    command: 'bash -c "python -u -m uvicorn run_api:app --host 0.0.0.0 --port 5172
      --reload --log-level debug"

      '
    container_name: openmanus-core-dev
    environment:
    - PYTHONUNBUFFERED=1
    - DOCKER_HOST=unix:///var/run/docker.sock
    - WORKSPACE_ROOT=/workspace
    - HOST_WORKSPACE_ROOT=./workspace
    - DEVELOPMENT=true
    - PYTHONFAULTHANDLER=1
    - PYTHONASYNCIODEBUG=1
    - MCP_HOST_MODE=true
    - MCP_HOST_IP=192.168.10.7
    - MCP_HOST_PORT=8001
    - LOG_LEVEL=DEBUG
    extra_hosts:
    - host.docker.internal:host-gateway
    networks:
    - openmanus-dev-network
    ports:
    - 5172:5172
    - 8765:8765
    security_opt:
    - seccomp=unconfined
    stdin_open: true
    tty: true
    volumes:
    - ./app:/app/app
    - ./config:/app/config
    - ./run_api.py:/app/run_api.py
    - ./requirements.txt:/app/requirements.txt
    - ./workspace:/workspace
    - /var/run/docker.sock:/var/run/docker.sock
    - ./docker-compose.dev.yml:/app/docker-compose.dev.yml
    - ./Dockerfile.dev.api:/app/Dockerfile.dev.api
    - ./scripts:/app/scripts
  openmanus-monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: openmanus-monitor
    depends_on:
    - openmanus-core-dev
    environment:
    - PYTHONUNBUFFERED=1
    - DEBUG_MODE=1
    extra_hosts:
    - host.docker.internal:host-gateway
    networks:
    - openmanus-dev-network
    ports:
    - 8089:8089
    restart: unless-stopped
    volumes:
    - ./workspace:/workspace
    - ./docker-compose.dev.yml:/app/docker-compose.dev.yml
    - ./monitor:/app/monitor
    - /var/run/docker.sock:/var/run/docker.sock
    - ./Dockerfile.dev.api:/app/Dockerfile.dev.api
    - ./requirements.txt:/app/requirements.txt
